# Generated by Django 5.0.4 on 2025-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('release_date', models.DateField()),
                ('youtube_trailer', models.URLField(blank=True, verbose_name='YouTube Trailer')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
